version: "3.8"

services:
  nginx:
    image: nginx:latest
    build: .
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - post_service
      - user_service
      - notification_service

  # client:
  #   image: client
  #   build: ./frontend
  #   restart: unless-stopped
  #   # ports:
  #   #   - 3000:3000
  #   depends_on:
  #     - nginx

  user_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - user-data:/data/db
    # ports:
    #   - "4002:27017"

  post_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - post-data:/data/db
    # ports:
    #   - "4001:27017"

  notification_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - notification-data:/data/db
    # ports:
    #   - "4000:27017"

  postobj:
    image: minio/minio:latest
    ports:
      - 9000:9000
      - 9050:9050 # it's must, else your image wont show in the frontend
    environment:
      - MINIO_ROOT_USER=2yScPd5Ss5BGuEUk
      - MINIO_ROOT_PASSWORD=mOLBN9GwA75veIWlmYU0mhlTTWeUkqyg
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - minio-data:/data

  user_service:
    build: ./backend/user_service
    ports:
      - 5010:5010
    depends_on:
      - user_db
    environment:
      - DB_URL=mongodb://user_db/userdb
      - ACCESS_TOKEN=fahad33 #! always use = sign for value assign
      - REFRESH_TOKEN=fahad12
      - ACCESS_TOKEN_EXPIRES=1h
      - REFRESH_TOKEN_EXPIRES=2d

  post_service:
    build: ./backend/post_service
    ports:
      - 5005:5000
    depends_on:
      - post_db
      - postobj
      - notification_db
    environment:
      - DB_URL=mongodb://post_db/postdb

  notification_service:
    build: ./backend/notification_service
    ports:
      - 5020:5020
    depends_on:
      - notification_db
    environment:
      - DB_URL=mongodb://notification_db/notifydb

volumes:
  user-data:
  post-data:
  notification-data:
  minio-data:
