version: "3"

services:
  # nodejs service
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo

  # mongodb service
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27019:27017"

  # minio service
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY='gzrTDeFKHhZgP4VhUFGi'
      - MINIO_SECRET_KEY='Siq8TfbHr5cYF3b3U2jvlmUKNUurnxtG0qLQtbsK'
    command: server --address 0.0.0.0:9000 /data

# volume
volumes:
  mongo-data:
