version: "3"

services:
  # nodejs service
  web:
    build: .
    ports:
      - 5020:5020
    depends_on:
      - mongo

  # mongodb service
  mongo:
    image: mongo:latest

    # it's necessary, if we we don't use it when the container is stopeed, the data will be erased
    # see README.md for details explanation
    volumes:
      - mongo-data:/data/db

    #! this host port must be DIFFERENT, as we're already running another mongo instance
    #! in user management service
    ports:
      - "27018:27017"

# volume
volumes:
  mongo-data:
# notes
# Using either a volume or a bind mount ensures that your MongoDB data persists even
# if the containers are stopped, removed, or recreated.
