version: "3"

services:
  # nodejs service
  web:
    build: .
    ports:
      - 5010:5010

    # we mention this environment variable because we need this value while executing
    # the codes inside this folder.
    environment:
      - ACCESS_TOKEN:'thisislabpc'
      - REFRESH_TOKEN:'thisislabpc'
      - ACCESS_TOKEN_EXPIRES:'1h'
      - REFRESH_TOKEN_EXPIRES:'2d'
    depends_on:
      - mongo

  # mongodb service
  mongo:
    image: mongo:latest

    # it's necessary, if we we don't use it when the container is stopeed, the data will be erased
    # see README.md for details explanation
    volumes:
      - mongo-data:/data/db
    ports:
      - "27020:27017"

# volume
volumes:
  mongo-data:
# notes
# Using either a volume or a bind mount ensures that your MongoDB data persists even
# if the containers are stopped, removed, or recreated.
