############ ERROR
version: "3"

services:
  # nodejs service
  web:
    build: .
    ports:
      - 5010:5010
    environment:
      - ACCESS_TOKEN:'thisislabpc'
      - REFRESH_TOKEN:'thisislabpc'
      - ACCESS_TOKEN_EXPIRES:'1h'
      - REFRESH_TOKEN_EXPIRES:'2d'
    depends_on:
      - mongo

  # mongodb service
  mongo:
    image: mongo:latest
    volumes: # it's necessary, as if we don't use it, then when the container stop the data will be removed
      - mongo-data:/data/db
    ports:
      - "27017:27017"

# volume
volumes:
  mongo-data:
# notes
# Using either a volume or a bind mount ensures that your MongoDB data persists even if the containers are stopped, removed, or recreated.
